version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: release
          command: npm run semantic-release || true
  docker-build:
    docker:
      - image: docker
    steps:
      - attach_workspace:
          at: ./
      - setup_remote_docker:
          reusable: true
      - run:
          name: Build Docker image
          command: |
            docker build -t quay.io/lowly2005/release-testing:$CIRCLE_BRANCH .
            if ["${CIRCLE_BRANCH}" == "master" && "${CIRCLE_TAG}" !== ""]; then
              echo "Building docker image for tag $CIRCLE_TAG"
              docker --build-arg git_tag=$(git describe --tags) tag quay.io/lowly2005/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
            fi
      - deploy:
          name: Push Docker image
          command: |
            echo $QUAY_PASS | docker login -u $QUAY_USER --password-stdin quay.io
            docker push quay.io/lowly2005/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
            if ["${CIRCLE_BRANCH}" == "master" && "${CIRCLE_TAG}" !== ""]; then
              docker push quay.io/lowly2005/release-testing:$CIRCLE_TAG
            fi
